### ISSUE TITLE
Incorrect transaction output index used to create a controlled output

### ISSUE THREAD

**Issue by jcvernaleo** [decred/Paymetheus#105]
While dcrd was still syncing, I made an address with my default account and sent 5DCR to it.  When dcrd was all sycned up and paymetheus was too, I had 5 DCR balance (correct).  I then sent 1 dcr out.  Looking at the tx history screen (attached below) I see the send, but the receive doesn't make sense (the 0.11.. tx could be change I guess, but why would the receiver get that and where is the tx actually providing the 5 dcr).  The negative balance in the tx list is also odd.

![tx](https://cloud.githubusercontent.com/assets/768163/16876636/a48b9f4a-4a72-11e6-84ba-8914f61f591a.png)

**Comment by jrick** [comment]
@jcvernaleo sent his wallet to me for further testing and I can confirm this bug.  Investigating whether this is a bug in the wallet's RPC server implementation or in paymetheus.

**Comment by jrick** [comment]
It's paymetheus, and the fix is a one liner.  PR'ing shortly.
