### ISSUE TITLE
Application fails to load when a dcrwallet instance is already running

### ISSUE THREAD

**Issue by jrick** [decred/Paymetheus#15]
Paymetheus runs dcrwallet as a background process.  If the application exits normally (both during clean and unclean shutdown from an unexpected exception) the dcrwallet process is terminated.  However, if Paymetheus is killed (e.g. through taskmgr) it is not given the opportunity to terminate the dcrwallet process.  There is no recourse for this except by manually killing the dcrwallet process as well.

It will also fail to load when a dcrwallet instance (or any other process) is using the same ports.  This prevents starting the new dcrwallet instance since it can not bind to the expected RPC listen addresses.

**Comment by marcopeereboom** [comment]
Debated renaming dcrwallet.exe to paymetheuswallet.exe in order to identify it.  Then if it is running on paymetheus restart we have a hint that it was not shutdown properly.  This will also prevent interactions with dcrwallet.exe if we choose a different default port.
