### ISSUE TITLE
Reintroduce seed restoring

### ISSUE THREAD

**Issue by jrick** [decred/Paymetheus#158]
This feature was removed before the 0.2.0 release due to it being untested and known issues with Paymetheus during rescans.  It needs to be added back so that both seeds can be imported from other wallets, as well as restores done using a Paymetheus seed backup (otherwise there is no point to forcing the user to make a backup).

**Comment by marcopeereboom** [comment]
A bit of a stretch goal for 0.5.0 but let's see if we can do this.
