### ISSUE TITLE
remove delay between launcher hiding and paymetheus show up.

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#162]
When paymetheus is launched it takes a second or two to show up due to dcrwallet starting in the background.  This is not a good UX so we should get rid of that "what's happening???" delay.

We can do that in a number of ways.
1) Immediately show paymetheus and launch dcrwallet in the background.  Grey out connect button while dcrwallet launches.
2) Provide feedback mechanism to launcher during formload.
3) Query task list to see if everyone is up

1 strikes me as ideal but we just need something that makes this prettier.  A different approach is fine too,

**Comment by jrick** [comment]
3 won't be possible because the launcher is not able to know via tasklist whether PM's window is visible yet or not.  The wait isn't for starting the wallet process, it's waiting for dcrwallet startup to complete and the rpc server to run.

**Comment by jrick** [comment]
launcher is planned to be removed instead (#288)
