### ISSUE TITLE
Launcher must start dcrd with custom appdata option

### ISSUE THREAD

**Issue by jrick** [decred/Paymetheus#165]
This 1) avoids interference with a typical cli install and 2) keeps the same paths as the batch script the installer previously placed in the start menu, so upgrades are smoother.

**Comment by jrick** [comment]
Nevermind, I misread the batch script.  It uses the standard appdata directory.  No need to change anything.

**Comment by marcopeereboom** [comment]
We decided to update dcrd files location at the same time as the db upgrade which will require an ibd.  This way folks that upgrade do not have to ibd twice.

**Comment by marcopeereboom** [comment]
After reevaluating this issue it has been decided that dcrd should use the default appdata locations so that paymetheus and dcrd only download the chain once.

https://github.com/decred/Paymetheus/pull/178 exists but will be closed.
