### ISSUE TITLE
Integrate paymetheus with stake pools

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#179]
There is a desire to integrate paymetheus with stake pools.  The idea would be to prompt the user for a username, password and pool and display/import pool information directly into paymetheus.

**Comment by jolan** [comment]
The first step probably would be to fetch a list of stakepools.  This is available in JSON format from the main website:

https://decred.org/api/?c=gsd

**Comment by marcopeereboom** [comment]
@jrick @jolan is writing a spec for this task.  You need to work with him on the details.

**Comment by jrick** [comment]
The stakepool API was implemented in https://github.com/decred/dcrstakepool/pull/48 so I believe we're ready to begin using this from Paymetheus.

**Comment by jolan** [comment]
The stake pool lister on decred.org needs to check if the pool has been upgraded and supports the API.  I will bug all the stake pool admins to upgrade too.

**Comment by jrick** [comment]
Too late to land this for 0.7.  The stakepool API updates just landed, and even if we did release with it, there won't be many pools that support the API anyways.  There are (updated) client libs in the Paymetheus codebase for this API. but nothing is hooked up yet.
