### ISSUE TITLE
Wallet Cannot Be Unlocked

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#184]
![image](https://cloud.githubusercontent.com/assets/4366787/19119977/12bbd25a-8ae7-11e6-9180-099415ccb75c.png)

On first sight, this seems like a double click that should have been a single click.  We will need to disallow that in the GUI.

**Comment by jrick** [comment]
There's not really enough information in this error message to figure out exactly what went wrong.

I need to know:

* ~~what was paymetheus doing (what view was shown) when this error occurred?~~ looks like it's at the public passphrase prompt
* was a button double clicked somehow, or did this happen after only one click?
* was some other error printed first, before this error was shown?
* what version of the software was used when this error occurred?

I'll look around but this might be unfixable with the current details.

**Comment by jrick** [comment]
Found the original issue report, with a few more details: https://forum.decred.org/threads/wallet-cannot-be-unlocked.4036/

**Comment by jrick** [comment]
Not sure if this is exactly the same issue the original reporter hit, but the button becomes clickable again after the wallet successfully opens.  If clicked again, while the wallet is syncing to the latest blocks and paymetheus is trying to sync itself to the wallet, this error is shown.

I think the solution is twofold;

* Do not make the button clickable again if the wallet did successfully open
* Add a new view after this dialog, a la the new restore from seed view, where it shows sync progress.  This is better UX than just doing work in the background with no user feedback.
