### ISSUE TITLE
There is no way to rescan for an imported script

### ISSUE THREAD

**Issue by jrick** [decred/Paymetheus#186]
Either a checkbox needs to be added to the import script dialog to call the RPC with the parameters to rescan the blockchain for the script, or we need a more general RPC to initiate rescans for all or some of the wallet's keys and scripts.  I like the second option better.  Need to think about an appropriate API for it so it can be added to the wallet.

**Comment by jrick** [comment]
The rescan RPC has been added to dcrwallet.  Implementing this only needs changes to Paymetheus now.

**Comment by karamble** [comment]
This is a serious problem. A lot of people running into dissapearing accounts and balances these days. There should be an option for a rescanwallet

**Comment by EmilioMann** [comment]
There are a lot of people with paymetheus accounts, tickets and coins "missing" from this problem. It's needed a patch for paymetheus asap.

**Comment by jrick** [comment]
Been mulling over this and i think something we want (in addition to a way to rescan from the import dialog) is to provide options to import any additional scripts when a wallet is restored.  This could cut down the number of required rescans from 1 + #scripts to just a single rescan.
