### ISSUE TITLE
Validate 0.8.0 release

### ISSUE THREAD

**Issue by jcvernaleo** [decred/Paymetheus#219]
Validate paymetheus on x86 and x64:
- [x] Windows 7 x64
- [x] Windows 10 x64

Make sure both icons launch paymetheus correctly.

In the comments note which OS you tested and the results.

**Comment by jcvernaleo** [comment]
It installs and starts on win7.

**Comment by jrick** [comment]
Tested on win10.  Was unable to do my normal testing due to an issue i'm assuming is related to slowness of my testing vm, but it is working on my host box.
