### ISSUE TITLE
Usability issues

### ISSUE THREAD

**Issue by fainges** [decred/Paymetheus#220]
Installed on Windows 10. Windows put links to testnet versions in recently added programs, not mainnet.
When the launcher is used, Paymetheus should skip the connection screen.
If no public passphrase is used, this screen should be skipped.

**Comment by jrick** [comment]
I agree about everything here except the testnet shortcuts.  We need those especially since one of the major points of this 0.8 release was the testnet hardfork demo, and it's much more confusing to tell people who want to run on testnet that they must manually make their own shortcuts (most people won't be able to and just give up).

**Comment by fainges** [comment]
I don't have a problem with having the shortcuts, the problem is that (on mine machine at least) Windows put them in the recently added section so they're the first thing you see when trying to start Paymetheus. I assume this is something that Windows 10 does, so it may not be in our control, or can we rearrange the order the shortcuts are created to promote the mainnet ones instead?

**Comment by jrick** [comment]
Sadly I don't think there is anything we can do about that.  Windows will just put any new start menu items at the top simply because they are new.

You should pin the correct shortcut you want as a tile or to the taskbar.

**Comment by rramires** [comment]
Have you thought about putting in a submenu and change names?
![menu](https://cloud.githubusercontent.com/assets/14129483/25530619/49838dac-2bfd-11e7-8ebe-67cc36b92ca3.jpg)

These extra icons make many startup users ask for help or give up using.

**Comment by jrick** [comment]
Plan is to make all but the launcher shortcut optional in the installer.  If users want standalone or testnet shortcuts, they will have to check those features during install.

**Comment by Porubay** [comment]
Every component of your website user experience should inspire trust. So, make sure all the written content within pages is informational and actual. Also, there are several peculiarities you should take into account[....](https://www.cleveroad.com/blog/the-elements-of-user-experience-as-a-way-to-become-trustworthy-in-customers--minds)
