### ISSUE TITLE
Purchase tickets tab should refresh automatically

### ISSUE THREAD

**Issue by chappjc** [decred/Paymetheus#226]
Returning to the Purchase tickets page to buy a ticket at least one price window later results in invalid values when the purchase ticket rpc is called.  Including expiry and spend limt.

expiry set to 64:
![expiry was "64"](https://cloud.githubusercontent.com/assets/9373513/23178540/ad5babc8-f81f-11e6-9090-a086be256414.png)

Also after setting to a large expiry, it then complained about spend limit.  After hitting refresh, everything worked to purchase one ticket.  This should happen automatically or at least the refresh button should flash or something.

**Comment by jrick** [comment]
sigh.. yes it should

*/me grumbles at the dev who originally wrote this view*
