### ISSUE TITLE
Use the new logo

### ISSUE THREAD

**Issue by jrick** [decred/Paymetheus#246]
Needs less illuminati

**Comment by linnutee** [comment]
decred-symbol-256px.svg
decred-symbol-256px.xaml

[decred-symbol-256px.zip](https://github.com/decred/Paymetheus/files/962734/decred-symbol-256px.zip)

**Comment by ta-lind** [comment]
Includes:
decred-symbol-256px-wpf.xaml
decred-symbol-256px–silverlight.xaml
decred-symbol-256px.ico
decred-symbol-256px.svg

[decred-symbol-256px.zip](https://github.com/decred/Paymetheus/files/962759/decred-symbol-256px.zip)
