### ISSUE TITLE
Offer to start dcrd for user

### ISSUE THREAD

**Issue by jrick** [decred/Paymetheus#25]
Having to remember the RPC credentials and running a dcrd instance in a command prompt on windows is not the greatest experience.

If the dcrd executable is found in the PATH, it could be possible for the user to simply click one button which will start dcrd (in a new console window, NOT as a background process) and then start the dcrwallet <-> dcrd RPC with the correct credentials.

Some things to think about:
- We need to verify that dcrd is the correct version before starting it.  This is why I believe semantic versioning entire applications (and not just APIs) is so important
- Can we check the dcrd signature to make sure we're not running a malicious binary?
- Perhaps starting dcrd as a service instead of in a new console window is better?  However, doing this will definitely prevent Paymetheus from ever being converted to a Windows Store application (using the [Project Centennial automatic conversion](https://msdn.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root) in Windows 10 Redstone).

**Comment by marcopeereboom** [comment]
I think this belongs on 0.1.0-alpha.

**Comment by jrick** [comment]
I'll assign this one to you but I think hitting 0.1.0-alpha means only fixing the features we already have, not adding more stuff to our plate.  The application is still functional without this feature, however nice it would be to have it.

**Comment by marcopeereboom** [comment]
I concede.  0.2.0-alpha sounds good to me.

**Comment by jrick** [comment]
Closing.  dcrd is now started by the launcher (https://github.com/decred/Paymetheus/issues/150), so that can be used instead of running Paymetheus directly if dcrd is to be used on the local computer.
