### ISSUE TITLE
Things that have caused many requests for help

### ISSUE THREAD

**Issue by rramires** [decred/Paymetheus#251]
Hi guys
I have seen many new users by clicking the wrong icon and asking for help in the Facebook group.
1-There are several icons to confuse. Even more by the wallet is called 'Paymetheus' and the correct icon to open in normal launch is 'Decred'.
![pay_icon](https://cloud.githubusercontent.com/assets/14129483/25500952/50c1e82a-2b67-11e7-901a-e81b3a21f4ab.jpg)

2-In version 1.0, there are still problems on the home screen in Paymetheus, which makes it impossible to spend the coins to buy tickets, send, etc.
I have solved this:
![paymetheus_en](https://cloud.githubusercontent.com/assets/14129483/25501009/88ebfa9c-2b67-11e7-98c2-78ef84124976.jpg)

3-So i have a suggestion that is simple to implement until can resolve the bugs: 
![suggestion](https://cloud.githubusercontent.com/assets/14129483/25501037/a0714532-2b67-11e7-9fb1-a54345480a08.jpg)

I hope I have helped
Thank you

**Comment by xaur** [comment]
+1 for only one shortcut for Windows wallet. All other options must be available for "advanced users" capable of creating custom shortcuts with extra command line arguments.

+1 for Rescan button. When people ask for help on support channel, they are often asked to delete everything and redownload. This is not cool imho. All my troubles were always solved with wallet rescan.

**Comment by gratefulcheddar** [comment]
@rramires, what kind of problems are you experiencing with the home screen for your 2nd point?

**Comment by rramires** [comment]
@gratefulcheddar
At 0.8.2 I still had 2900DCR.
I bought 12 tickets + - 500DCR and i sent 500DCR to Poloniex. 
The money arrived and the purchase took many blocks but worked. I checked this on the pool.
On the home screen, it continued displaying 2900DCR and without discounting the 500DCR
It was as if I did not buy the tickets.
So the wallet would not let me buy more, saying the coins were stuck.

I upgraded to 1.0 in the hope of solving it and nothing.
Just solved deleting the folder date and lowering the entire blockchain.
Now it is correct showing 2400DCR. 

Some people said they had this problem when you try to spend. Only downloading  blockchain and rescanning the values resolve. 
It seems that while screen does not update and should have some 'validator' that does not let spend.

It looks like you download blochchain again, solve most of Paymetheus's problems.
My and other users. 
So I gave the idea of a button(Refresh) to redo a scan from an X number of previous blocks.

**Comment by jrick** [comment]
Many of these are already known issues by the team and have issues opened for them.  So let's go one by one:

1) The start menu shortcuts are placed by the installer.  Please bring this up in this repo: https://github.com/decred/decred-windows-installer/

2) Known issue, see #233 and #225

3) I'll consider this.  Can you open a new issue for tracking just this?

**Comment by rramires** [comment]
Ok. Thanks

**Comment by jrick** [comment]
I made an issue for tracking the rescan idea: #262

Going to close this now since all of the issues have been addressed or discussion has been moved to their own issues.  Thank you for the feedback.
