### ISSUE TITLE
Paymetheus fails to launch if Windows user name has & in it

### ISSUE THREAD

**Issue by davecgh** [decred/Paymetheus#254]
As the title indicates, if your windows username has an `&` in it, Pametheus fails to launch.

The error is "consensus server exited with code 1".

**Comment by jrick** [comment]
Paymetheus or the launcher?

**Comment by jrick** [comment]
This is decred/dcrd#713 and will be fixed whenever the logger is replaced.

**Comment by jrick** [comment]
This should be fixed in the next release as the logger changes have made their way to dcrd and dcrwallet.
