### ISSUE TITLE
Importing scripts: redeem string does nothing

### ISSUE THREAD

**Issue by selekta** [decred/Paymetheus#302]
Hi!

When I try to import a script, put in the script raw hex and passphrase and then click OK nothing at all happens.

**Comment by jrick** [comment]
There is a lack of feedback from this dialog.  When you import a script, if no error message is shown, it is successfully imported. If you didn't run a rescan, this operation is finished, however if you also selected to do a rescan for relevant outputs after importing the script, the rescan will just run in the background without any feeback.  The rescan was a new addition to the program and we don't have a way to show the progress at this time, so it will just complete in the background and you may or may not see more transactions shown as the rescan completes.

**Comment by selekta** [comment]
Thank you!
