### ISSUE TITLE
dll issue

### ISSUE THREAD

**Issue by jcvernaleo** [decred/Paymetheus#308]
Was reported on forum:

Unable to load penimc.dll when starting up.

From the post:

Searched for "penimc.dll," looks like it's a little piece of info in certain touch-aware applications that gets corrupted if you have ever updated MS .Net from version 2.0 to any later version. Basically, the update unregisters the .Net 2.0 version of the .DLL and "forgets" to re-register the new one, so touch-aware apps don't know where to find it. Easy enough solution, just use good old regsvr32 to re-register the missing DLLs.
(This handwaves about half an hour of mucking about and searching for error codes that finally led me to realizing I need to be running regsvr32 in Admin mode)

@jrick is this a known thing (I seem to remember some .Net version thing in the past) or something new that we need to track?

**Comment by jrick** [comment]
This is the first I've seen this issue and i don't know of a good solution.  Not much we can do when .net doesn't work as expected even if it is at the correct version.  Best thing to do would be to document the workaround.

**Comment by jcvernaleo** [comment]
@jrick this issue is pretty old.  Since PM isn't really getting much love these days anyway, think it is okay to just close it with a 'won't fix'?
