### ISSUE TITLE
Not seeing transaction 

### ISSUE THREAD

**Issue by TheDarkCryptoMiner** [decred/Paymetheus#310]
I have a transaction from a pool that says unspent, but isn't in my wallet/paymetheus. I have restored from seed and rescanned. I also tried manually running the dcrd and that didn't work either.. I am fully synced and it doesn't show.

Transaction was posted in:
https://mainnet.decred.org/tx/9afe70f6f67fe08785c31e041977ce80ab2336f28e5c7ba43c10229499a304ff

OP_DUP OP_HASH160 8cc848ec28f9a2a33dcf23aa51b5644f007e4461 OP_EQUALVERIFY OP_CHECKSIG
DsWgC3o3jXtWi8ZM3USNYS7qBQE3E3mhXr5 - 0.19511887 DCR (U) (unspent)

Viewing the transfer to the address the 0.195... is there

Transactions:
https://mainnet.decred.org/address/DsWgC3o3jXtWi8ZM3USNYS7qBQE3E3mhXr5 

Any idea on how to get it in my wallet?

**Comment by jrick** [comment]
There appears to be two other transactions involving that address, according to the block explorer.  Do you see those?

**Comment by TheDarkCryptoMiner** [comment]
Hi @jrick  thanks for the reply - yeah, the original posting of the .26..DCR I got no problem and then sent it to my bittrex account - hence the remaining balance of the 0.19.... being the amount that I can't seem to get into my wallet.

**Comment by jrick** [comment]
And just to confirm, this was with the same wallet?  You see those transactions in your reseeded history right now?

**Comment by TheDarkCryptoMiner** [comment]
Actually, I just realised I am being dumb. It went direct to Bittrex. It is there. Apologies for the goose chase.
