### ISSUE TITLE
Can't connect to dcrd popup is not human readable.

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#32]
There is too much jargon in the popup failure dialog.  It should print a human readable error instead.

**Comment by tpruvot** [comment]
![capture d ecran 2016-07-26 01 11 50](https://cloud.githubusercontent.com/assets/145119/17120849/65c8a072-52cf-11e6-8a05-293399597ce3.png)

**Comment by jrick** [comment]
The encoding issue is separate from this issue (which is about replacing the rpc status object with more user-friendly text).  I'll open a new issue for the encoding problems.
