### ISSUE TITLE
Remember if there is a wallet db password

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#48]
Now that we have a defaults.ini we can use it to store additional information.

For example, we should save if there is the need for a wallet database password.  If there isn't we can skip the dialog prompting the user for it.

Implementing this requires defaults.ini to be used a bit more clever than currently is the case.  At this time it is overwritten every time.  This needs to become a merge and rewrite.

**Comment by jrick** [comment]
paymetheus no longer prompts for the public passphrase if it is unset.
