### ISSUE TITLE
New accounts don't show up in Accounts pane.

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#50]
When a new account is created it is not displayed in the GUI.

Account cannot be selected in "create transaction", "request payment"  and "history" panes (this one is known and tracked in another issue).

Account is created underneath because trying to add an account with the same name results in a dup account error.

**Comment by marcopeereboom** [comment]
The issue is slightly different.  When paymetheus is closed and openebd again the new accounts do show up.

This is very confusing for users and must be fixed.

**Comment by jrick** [comment]
Yep this broke when we got new viewmodels for the new RFP0001 views.  Just need to add the right data to the viewmodels when the notification is received from the Wallet event.
