### ISSUE TITLE
Reveal link in defaults pane doesn't do anything.

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#52]
When the default account is revealed by clicking the triangle there is a "Reveal" link that appears.  Clicking it does nothing.

Additionally all information that is revealed seems to not be plugged in.  It looks like all these are related issues.

It shows the following:
"Public key address    Reveal    Aa"

**Comment by jrick** [comment]
We can probably can this feature for first release.  The public key was intended for use with stake pools.

**Comment by marcopeereboom** [comment]
Then let's remove it from the ui.
