### ISSUE TITLE
Published transaction should display transaction id

### ISSUE THREAD

**Issue by marcopeereboom** [decred/Paymetheus#74]
This message box should show a selectable label with the transaction id.

<img width="144" alt="published" src="https://cloud.githubusercontent.com/assets/4366787/16596959/f4f21676-42bb-11e6-824f-3d73e137b5c3.PNG">

**Comment by jrick** [comment]
See #18.  MessageBox is a Winforms feature, we shouldn't be depending on it in a WPF app.  I don't even know if it's possible to make text in MessageBoxes selectable.

We can display the transaction hash somewhere else in the create transaction view after it is published.

**Comment by marcopeereboom** [comment]
Honestly I hate the message box altogether but we need some sort of indicator to the user.

Not sure if this is the right spot to complain about it but the sign button should be disabled upon click.

**Comment by marcopeereboom** [comment]
Per discussion don't use a message box; use a copy/pastable label instead.

**Comment by jrick** [comment]
![image](https://cloud.githubusercontent.com/assets/1420313/17215738/e65535ba-54ab-11e6-9bed-1a2e27394d1d.png)
