### ISSUE TITLE
UI Enhancements

### ISSUE THREAD

**Issue by cjepson** [decred/Paymetheus#85]
- Strip logos until consensus is reached on vector formats for these
- Remove extra light blue colour and replace with the already used teal
- Fix default sizing of the main window so that elements in all views will fit in it with the default size
- Clean up views regarding the seed, such as adjust text box sizes and making the importance of storing the seed more obvious
- Add an icon for the program

**Comment by marcopeereboom** [comment]
These are 5 issues.  Please write them up as individual issues so that we can assign them to the proper release.

I'll close this for now to prevent dupes.
