### ISSUE TITLE
Cannot unexpand accounts

### ISSUE THREAD

**Issue by jcvernaleo** [decred/Paymetheus#88]
In the accounts tab, when you expand (click the triangle) an account, it expands properly.  But, you cannot unexpand it.  Need to go to a different tab and back to unexpand.

**Comment by jrick** [comment]
Will look into this for 0.2.0.  The accounts list uses a ListBox, and the selected item is styled using a trigger to show the expanded view when selected.  Only by selecting another account can the current expanded account be unexpanded.

ListBox may not be the right component to display this data and switching it is probably not trivial, hence the 0.2.0 milestone.  Perhaps there is an easy way to configure the ListBox to select and deselect items with a single click...

**Comment by jrick** [comment]
This may be a workable solution: http://stackoverflow.com/questions/5139956/listbox-with-single-select-and-also-unselect-on-click/5144092#5144092

**Comment by marcopeereboom** [comment]
This issue doesn't bother me much.  It is just inconsistent.  Next release is fine.

**Comment by marcopeereboom** [comment]
Dup of #51
